CREATE OR REPLACE WAREHOUSE FIFA_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE FIFA_DB;

CREATE OR REPLACE SCHEMA FIFA_DB.MARKETING;

USE WAREHOUSE FIFA_WH;
USE DATABASE FIFA_DB;
USE SCHEMA MARKETING;