[connections.snowflake]
account = "xxxxxx"
user = "xxxxxxxx"
password = "xxxxxxxx"
role = "ACCOUNTADMIN"
warehouse = "FIFA_WH"
database = "FIFA_DB"
schema = "MARKETING"

[openai]
api_key = "xxxxxxxxxxxxxxxxxx" 